<a href="https://colab.research.google.com/github/wankhadearpit21-pixel/Python-Project/blob/main/Task_20_optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("./House Price India.csv")
df

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,42734,2,1.50,1556,20000,1.0,0,0,4,...,1957,0,122066,52.6191,-114.472,2250,17286,3,76,221700
14616,6762830339,42734,3,2.00,1680,7000,1.5,0,0,4,...,1968,0,122072,52.5075,-114.393,1540,7480,3,59,219200
14617,6762830618,42734,2,1.00,1070,6120,1.0,0,0,3,...,1962,0,122056,52.7289,-114.507,1130,6120,2,64,209000
14618,6762830709,42734,4,1.00,1030,6621,1.0,0,0,4,...,1955,0,122042,52.7157,-114.411,1420,6631,3,54,205000
14619,6762831463,42734,3,1.00,900,4770,1.0,0,0,3,...,1969,2009,122018,52.5338,-114.552,900,3480,2,55,146000

In [ ]:
x = df.drop('Price',axis=1)
y = df['Price']
print(" Independent Features (X) :")
print(x.columns)
print("\nDependent Feature (Y) :")
print(y.name)
print("\nShape of x :")
print(x.shape)
print("Shape of y :")
print(y.shape)

 Independent Features (X) :
Index(['id', 'Date', 'number of bedrooms', 'number of bathrooms',
       'living area', 'lot area', 'number of floors', 'waterfront present',
       'number of views', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport'],
      dtype='object')

Dependent Feature (Y) :
Price

Shape of x :
(14620, 22)
Shape of y :
(14620,)

In [ ]:
cat_cols = df.select_dtypes('object').columns
print("Categorical columns :")
print(cat_cols)

num_cols = df.select_dtypes('int','float').columns
print("\nNumerical columns :")
print(num_cols)
num_cols = num_cols.drop('Price')

Categorical columns :
Index([], dtype='object')

Numerical columns :
Index(['id', 'Date', 'number of bedrooms', 'living area', 'lot area',
       'waterfront present', 'number of views', 'condition of the house',
       'grade of the house', 'Area of the house(excluding basement)',
       'Area of the basement', 'Built Year', 'Renovation Year', 'Postal Code',
       'living_area_renov', 'lot_area_renov', 'Number of schools nearby',
       'Distance from the airport', 'Price'],
      dtype='object')

In [ ]:
encoded = pd.get_dummies(df)
encoded.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[num_cols])
scaled_df = pd.DataFrame(scaled_features, columns=num_cols)
scaled_df

,id,Date,number of bedrooms,living area,lot area,waterfront present,number of views,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Renovation Year,Postal Code,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport
0,-1.713148,-1.685908,1.726515,1.671691,-0.159376,-0.087863,4.916126,2.363238,1.972420,1.880848,-0.036740,-1.692844,-0.218461,-1.575444,1.278160,-0.282203,-0.014981,-0.777886
1,-1.634590,-1.685908,0.661197,0.885260,-0.292557,-0.087863,-0.304223,2.363238,0.270281,0.129789,1.590777,-2.099726,-0.218461,-1.523037,0.684877,-0.335930,-0.014981,-1.561260
2,-1.576392,-1.685908,1.726515,0.874487,-0.148036,-0.087863,-0.304223,-0.648227,0.270281,1.329145,-0.660993,-1.082522,-0.218461,-1.523037,1.364982,-0.236151,-1.238588,-1.337439
3,-1.318751,-1.685908,0.661197,1.305408,0.735916,-0.087863,-0.304223,-0.648227,1.121351,1.808887,-0.660993,1.019699,-0.218461,-1.470631,1.958265,1.154887,1.208625,1.236505
4,-1.268409,-1.685908,-0.404121,0.659026,-0.279371,-0.087863,-0.304223,0.857506,0.270281,0.093809,1.189472,-1.421590,-0.218461,-1.418225,0.091594,-0.316742,-1.238588,-1.561260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,1.510170,1.922341,-1.469439,-0.584182,0.129402,-0.087863,-0.304223,0.857506,-0.580788,-0.294782,-0.660993,-0.472200,-0.218461,1.726138,0.366530,0.173942,1.208625,1.236505
14616,1.524439,1.922341,-0.404121,-0.450596,-0.213440,-0.087863,-0.304223,0.857506,-0.580788,-0.146062,-0.660993,-0.099225,-0.218461,2.040574,-0.660863,-0.202379,1.208625,-0.665975
14617,1.569169,1.922341,-1.469439,-1.107751,-0.236648,-0.087863,-0.304223,-0.648227,-1.431857,-0.877669,-0.660993,-0.302666,-0.218461,1.202077,-1.254146,-0.254571,-0.014981,-0.106422
14618,1.583759,1.922341,0.661197,-1.150843,-0.223435,-0.087863,-0.304223,0.857506,-1.431857,-0.925643,-0.660993,-0.540013,-0.218461,0.468393,-0.834507,-0.234961,1.208625,-1.225528
14619,1.704643,1.922341,-0.404121,-1.290892,-0.272250,-0.087863,-0.304223,-0.648227,-1.431857,-1.081559,-0.660993,-0.065318,4.608517,-0.789353,-1.586963,-0.355886,-0.014981,-1.113618

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

print(y_pred[:10])

print(y_test.iloc[:10])

[242347.25653076 657370.41860962 576845.09857178 546174.12576294
 573203.18005371 130588.1529541  874623.01309204 386042.01147461
 896748.0256958  609710.87918091]
3837      235000
4098      552000
357       615000
11768     555000
9751      649950
11808     257700
4764      980000
1650      535000
3015     1030000
8628      549950
Name: Price, dtype: int64

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.7462793385287378

In [ ]:
print(num_cols)

Index(['id', 'Date', 'number of bedrooms', 'living area', 'lot area',
       'waterfront present', 'number of views', 'condition of the house',
       'grade of the house', 'Area of the house(excluding basement)',
       'Area of the basement', 'Built Year', 'Renovation Year', 'Postal Code',
       'living_area_renov', 'lot_area_renov', 'Number of schools nearby',
       'Distance from the airport'],
      dtype='object')

In [ ]:
import joblib

# Save the trained Linear Regression model
joblib.dump(model, "House Price India.pkl")

# Save the StandardScaler object
joblib.dump(scaler, "scaler.pkl")

# Save the list of feature columns
joblib.dump(num_cols.tolist(), "columns.pkl")

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!